apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.release }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
  selector:
    release: {{ .Values.release }}
status:
  loadBalancer: {}
